name: firstworkflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3
      
      - name: create go module
        run: go mod init main
      
      - name: build go app
        run: go build main.go

      - name: docker version
        run: docker -v

      - name: docker image list
        run: docker image ls

      - name: docker login
        run: docker login --username ${{ secrets.dockerusername }} --password ${{ secrets.dockerpassword }}

      - name: docker duild
        run: docker build -t chaitanyajarajapu/mymultiimage:10.0 .

      - name: docker image list
        run: docker image ls
        if: always()

      - name: docker image push
        run: docker push chaitanyajarajapu/mymultiimage:10.0

      - name: Azure login with Github action
        uses: azure/login@v1
        with:
          creds: '${{ secrets.azurecredentials}}'

      - name: Azure login command
        run: |
          az account show
          az group list
  


