name: firstworkflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3
      
      - name: create go module
        run: go mod init main
      
      - name: build go app
        run: go build main.go

      - name: docker version
        run: docker -v

        


  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Second step
        run: echo "Second Step"

  


